export const posts = [
  {
    slug: "devops-unleashed",
    title: "DevOps Unleashed",
    excerpt: "Master CI/CD, automation, and cloud strategies in Chicago.",
    content: "",
    image: "/images/post1.png",
    author: "Admin",
    publishedAt: "2024-09-01",
  },
  {
    slug: "mobile-dev-summit",
    title: "Mobile Development Summit",
    excerpt: "Explore the future of mobile apps in Los Angeles.",
    content: "",
    image: "/images/post2.png",
    author: "Admin",
    publishedAt: "2024-10-01",
  },
  {
    slug: "cybersecurity-conference",
    title: "Cybersecurity Conference",
    excerpt: "Stay ahead of security threats at this Boston-based conference.",
    content: "",
    image: "/images/post3.png",
    author: "Admin",
    publishedAt: "2024-11-01",
  },
  {
    slug: "data-science-hackathon",
    title: "Data Science Hackathon",
    excerpt: "A 72-hour hackathon focused on data-driven innovation in San Diego.",
    content: "",
    image: "/images/post4.png",
    author: "Admin",
    publishedAt: "2024-12-01",
  },
  {
    slug: "cloud-native-meetup",
    title: "Cloud Native Meetup",
    excerpt: "Discuss Kubernetes and cloud-native trends in Portland.",
    content: "",
    image: "/images/post5.png",
    author: "Admin",
    publishedAt: "2025-01-01",
  },
  {
    slug: "frontend-masters",
    title: "Frontend Masters Conference",
    excerpt: "Advance your frontend expertise in Nashville.",
    content: "",
    image: "/images/post6.png",
    author: "Admin",
    publishedAt: "2025-02-01",
  },
];
